#' surveydetails
#' 
#' Get detailed information about a survey
#' 
#' \code{sureydetails()}This function calls the SurveyMonkey API using the current oauth token and returns
#' details about a survey including the number of pages, questions, answer choices,
#' urls, etc...
#' 
#' \code{surveyquestions()}This function extracts a named character vector of question wordings
#' from a \dQuote{sm_survey} object. This can be useful for creating a codebook of responses or for mapping 
#' responses (from \code{\link{getresponses}}) to the original question wordings.
#' 
#' \code{surveypreview} opens a survey preview url in a web browser via \code{\link[utils]{browseURL}}.
#' 
#' @param survey A sm_survey object, as retrieved by \code{surveylist()}.
#' @param question_detail A logical value to indicate whether to include details on questions and answer choices.  By default = TRUE.
#' @param oauth_token Your OAuth 2.0 token, as generated by \code{smlogin}. By default, retrieved from \code{getOption('sm_oauth_token')}.
#' 
#' @return A list of objects of class \code{sm_survey}.
#' @references SurveyMonkey API V3 at \url{https://developer.surveymonkey.com/api/v3/#surveys}
#' @export surveydetails
#' @export print.sm_survey
#' @export surveyquestions
#' @export surveypreview
#' @keywords 
#' 
#
# This function returns details about a SurveyMonkey survey in the list structure based on the
# JSON response format
#
# $response_count : int = total number of responses
# $pages_count : int = number of pages in the survey
# $buttons_text : list of chr = display text for buttons
# $custom_variables : named list = ?
# $nickname : chr = short name for survey
# $id : chr = SurveyMonkey id for the survey
# $question_count : int = total number of questions on the survey
# $category : chr = broad category for survey 
# $preview : chr = web browsable url to preview the survey
# $is_owner : logical = is user owner of the survey(?)
# $language : chr = langauge the survey is written in
# $date_modified : chr = date/time when survey was last modified
# $title : chr = survey title
# $analyze_url : chr = web browsable url to analyze responses
# $pages : list
#   $ href : chr = api accessible weblink for data on this page
#   $ description : chr = text displayed at top of page
#   $ questions : list = length is the number of questions on the page
#     $ display_options : list
#       $ show_display_number : logical 
#     $ sorting : 
#       $ type : (e..g, random)
#       $ ignore_last
#     $ family : chr = general style of question (e.g., matrix, single-choice)
#     $ subtype : chr = detailed style of question (e.g., single)
#     $ required :
#       $ text: chr = text to display if not answered(?)
#       $ amount : chr = 
#       $ type : chr = ?
#     $ answers : list
#       $ rows :  list = used in matrix questions to store row headings
#         $ visible
#         $ text
#         $ position
#         $ id
#       $ choices : list
#         $ description : chr = (used in matrix questions?)
#         $ weight : int = (used in matrix questions?)
#         $ is_na : logical = (used in matrix questions?)
#         $ visible : logical 
#         $ text : chr = answerchoice text
#         $ position : int = answerchoice position
#         $ id : chr = answerchoice id
#     $ visible : logical 
#     $ href : api accessible weblink for this question
#     $ headings : list
#     $ heading : chr = HTML text displayed with question
#     $ position : int = display position for question on the page
#     $ validation : 
#     $ id : chr = id for the question
#     $ forced_ranking : logical 
#   $ title : chr
#   $ position : int
#   $ id : id for page
#   $ question_count : int = number of questions on this page
# $summary_url : chr = web browsable url for survey summary
# $href : chr = api accessible web link for survey data
# $date_created : chr = date survey originally created
# $collect_url : chr = web browsable url to collect responses
# $edit_url : chr = web browsable url to edit the survey

surveydetails <- function(
    survey,
    question_details = TRUE,
    oauth_token = getOption('sm_oauth_token'),
    ...
){
    if(inherits(survey, 'sm_survey'))
        survey <- survey$id
    if(question_details) {
      u <- paste('https://api.surveymonkey.net/v3/surveys/',survey,'/details?',sep='')  
    }
    else 
      u <- paste('https://api.surveymonkey.net/v3/surveys/',survey,'?',sep='')  
    if(!is.null(oauth_token)) {
      token <- paste('bearer', oauth_token)
    }
    else
        stop("Must specify 'oauth_token'.  Try using smlogin() first.")
    h <- httr::add_headers(Authorization=token,
                     'Content-Type'='application/json')
    out <- httr::GET(u, config = h, ...)
    httr::stop_for_status(out)
    parsed_content <- httr::content(out, as = 'parsed')
    structure(parsed_content, class = "sm_survey")
}

surveyquestions <- function(survey){
    d <- surveydetails(survey, oauth_token = getOption('sm_oauth_token'), question_details = TRUE)
    questions <- unlist(unlist(lapply(d$pages, `[`, "questions"), recursive = FALSE), recursive = FALSE)
    n <- unname(unlist(lapply(questions, `[`, "id")))
    w <- unname(unlist(lapply(questions, `[`, "headings")))
    w <- gsub("<.*?>", "", w)
    structure(w, names = n, class = c("character", "sm_surveyquestions"))
}

surveypreview <- function(survey) {
    d <- surveydetails(survey, oauth_token = getOption('sm_oauth_token'))
    browseURL(d$preview)
}

print.sm_survey <- function(x, ...){
  if(!is.null(x$title)) 
    cat('Survey Title:', x$title, '\n')
  if(!is.null(x$nickname))
    cat('Survey Nickname:', x$nickname, '\n')
  if(!is.null(x$id))
    cat('ID:', x$id, '\n')
  if(!is.null(x$language))
    cat('Language:', x$language, '\n')
  if(!is.null(x$question_count))
    cat('No. of Questions:', x$question_count, '\n')
  if(!is.null(x$response_count))
    cat('Respondents:', x$response_count, '\n')
  if(!is.null(x$preview))
    cat('Preview URL:', x$preview, '\n')
  if(!is.null(x$analyze_url))
    cat('Analysis URL:', x$analyze_url, '\n')
  if(!is.null(x$date_created))
    cat('Date Created: ', x$date_created, '\n')
  if(!is.null(x$date_modified))
    cat('Date Modified:', x$date_modified, '\n')
  if(!is.null(x$pages))
    cat('Survey Pages:', length(x$pages), '\n')
  invisible(x)    
}

