#' userdetails
#'
#' Obtains information about SurveyMonkey user.
#'
#' This function calls the SurveyMonkey API using the current oauth token and returns
#' information about the SurveyMonkey user and account associated with the token.  It can be used
#' as a "Hello World" after \code{smlogin}
#'
#' @param oauth_token Your OAuth 2.0 token, as generated by \code{\link{smlogin}}. By default, retrieved from \code{getOption('sm_oauth_token')}.
#' @return An object of class \code{sm_userdetails}.
#' @references SurveyMonkey API V3 at \url{https://developer.surveymonkey.com/api/v3/#users-me}


userdetails <- function(oauth_token = getOption('sm_oauth_token'), ...) {
  u <- 'https://api.surveymonkey.net/v3/users/me'
  if (!is.null(oauth_token))
    token <- paste('bearer', oauth_token)
  else
    stop("Must specify 'oauth_token'.  Try smlogin() first to get a token.")
  out <- GET(u, config = add_headers(Authorization = token,
                                  'Content-Type' = 'application/json'))
  stop_for_status(out)
  content <- content(out, as='parsed')
  structure(content, class = "sm_userdetails")
  return(content)
}